name: Branch Checks
description: Action to run branch checks for code consistency

runs:
  using: composite
  steps:
    - name: Lint & Check Formatting
      shell: bash
      run: pnpm lint

    - name: Typecheck
      shell: bash
      run: pnpm typecheck

    # - name: Test
    #   shell: bash
    #   run: pnpm test

    # Add additional branch checks here.
    # i.e. Translations, security, and any other additional checks
