name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Branch Checks
        uses: ./.github/actions/branch-checks

      - name: Build Apps and Packages
        run: pnpm build
